version: "3"
services:
  backend:
    build: .
    environment:
      - NODE_ENV=production
      - MONGODB_CONNECTION=mongodb://mongo:27017/unitedbank
      - ORIGIN=http://localhost:3000
      - JWT_SECRET=test
      - PORT=5000
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"