apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: backend
          image: narensj/unitedbank-backend:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_CONNECTION
              value: "{{ .Values.MONGODB_CONNECTION }}"
            - name: JWT_SECRET
              value: "test"
            - name: ORIGIN
              value: "*"
          ports:
            - containerPort: 5000