#Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}        
    spec:
      containers:
        - name: frontend
          image: narensj/unitedbank-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80