name: 'Deploy'
on: 
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          echo "${{ secrets.MONGODB_CONNECTION }}"
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade unitedbank ./helm --install --wait --atomic --set=MONGODB_CONNECTION=${{ secrets.MONGODB_CONNECTION }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'
